### PR TITLE
update smart contract to compatible with new BrightID customized veri…

### PR DESCRIPTION
**Pull request by siftal**
…fication

### CODE REVIEW

**Comment by xuhcc** [comment]
What is verification expression? I can't find it in BrightID documentation.

**Comment by siftal** [comment]
We have some different verification in BrightID, by verification expersion you can add a new parameter to the GET /verifications/{context}/{contextId} to enable your app pass an expression like:
verification=((SeedConnected and SeedConnected.timestamp > 1604130920901) or SeedConnectedWithFriend) and (Yekta and Yekta.rank >= 3)
to this endpoint and get customized verification from the node.
Otherwise, you can only get BrightID verification.

**Comment by adamstallard** [comment]
> 
> 
> What is verification expression? I can't find it in BrightID documentation.

We need to update the documentation to include verification expressions.

**Comment by auryn-macmillan** [comment]
What's going on with this PR? Have the changes been implemented somewhere else?

**Comment by auryn-macmillan** [comment]
Closing because this looks stale.

**Pull request closed without merging**
