### PR TITLE
Add batch 64 verifier contracts and maci parameters

### PR DESCRIPTION
**Pull request by yuetloo**
@auryn-macmillan , @pettinarip , @samajammin, I'm not sure if this PR is the same as PRs: #493 and #484

### CODE REVIEW

**Comment by yuetloo** [comment]
I still need to update the doc with instructions to build the c binaries if they crash loading the JSON input files.

@pettinarip, I'm not sure if your PR #493 is related to this PR..

**Comment by pettinarip** [comment]
> @pettinarip, I'm not sure if your PR #493 is related to this PR..

Well yes, it's kind of related, in that PR I just wanted to put somewhere the ipfs hash for the 64 params so that everyone could access it in any case but I haven't done any of your good work here.
As I mentioned there, I haven't pinned them in Pinata, would be nice if someone could do it. I don't have a paid account. Not sure if there is one in the clrfund team to do so.

**Comment by yuetloo** [comment]
> > @pettinarip, I'm not sure if your PR #493 is related to this PR..
> 
> Well yes, it's kind of related, in that PR I just wanted to put somewhere the ipfs hash for the 64 params so that everyone could access it in any case but I haven't done any of your good work here. As I mentioned there, I haven't pinned them in Pinata, would be nice if someone could do it. I don't have a paid account. Not sure if there is one in the clrfund team to do so.

Copying @auryn-macmillan to pin the files in pinata. Please also make sure to rename the files with the suffix `Custom` to `32` as from my test, that's how MACI finds the input files and the c binaries because of this line here:

https://github.com/privacy-scaling-explorations/maci/blob/master/cli/ts/genProofs.ts#L265

**Comment by auryn-macmillan** [comment]
Here are the pinned 64 batch params `QmbVzVWqNTjEv5S3Vvyq7NkLVkpqWuA9DGMRibZYJXKJqy`

Might take a little while for it to be available on some gateways, but you should be able to reliably [get them from Pinata](https://gateway.pinata.cloud/ipfs/QmbVzVWqNTjEv5S3Vvyq7NkLVkpqWuA9DGMRibZYJXKJqy) I think. Nevertheless, I'll try to leave my local IPFS node running for a few days as well.

**Comment by auryn-macmillan** [comment]
@yuetloo, is this one good to go?

**Comment by yuetloo** [comment]
> @yuetloo, is this one good to go?

Yes, could you please do a quick review to see if the documentation is sufficient? Also, should the verifier contracts be renamed to match the ethStaker branch naming convention? e.g. `QuadVoteTallyVerifier32Batch64.sol`

Here's the batch 16 verifier from the ethStaker branch:
[contracts/contracts/snarkVerifiers/QuadVoteTallyVerifier32Batch16.sol ](https://github.com/clrfund/monorepo/blob/0915a92c98aac26ebce0b9f6d3437968dd476f17/contracts/contracts/snarkVerifiers/QuadVoteTallyVerifier32Batch16.sol)

**Review by auryn-macmillan — APPROVED** [review]
lgtm

**Pull request merged**
